### ISSUE TITLE
Removing the polar label does not remove the description

### ISSUE THREAD

**Issue by niccokunzmann** [polarsource/polar#1000]
I just removed the `polar` label from an issue and I would expect it to remove the polar description below the issue.
I wonder how to badge-edit/change this description. What is the consistent GUI to use edit the text below the issues?

https://github.com/niccokunzmann/python-recurring-ical-events/issues/92

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/polarsource) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog :^)

<a href="https://polar.sh/polarsource/polar/issues/1000">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/polarsource/polar/issues/1000/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/polarsource/polar/issues/1000/pledge.svg">
</picture>
</a>

**Comment by zegl** [comment]
Hey again. This happens when the repository has been configured to _badge_ all issues automatically. To remove the badge from this specific issue, remove it manually from the description by editing it on Github.

You can change the settings for which issues to badge on polar.sh on the "Promote" / "Issues" page. From there you can also trigger a removal of the badge from all issues in a repo.
