### ISSUE TITLE
Maintainer vs. backer profile shown on pledge page

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#1044]
From the new backer dashboard if I enter an issue link, I'm redirected to the pledge page, but the state of the profile selector defaults to the maintainer vs. current active. We should set this in our Zustand store to carry it over.

<img width="1547" alt="image" src="https://github.com/polarsource/polar/assets/281715/33039c29-7346-4991-85cf-4364b8432369">

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/polarsource) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog :^)

<a href="https://polar.sh/polarsource/polar/issues/1044">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/polarsource/polar/issues/1044/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/polarsource/polar/issues/1044/pledge.svg">
</picture>
</a>

**Comment by zegl** [comment]
I think that the bug here is in the profile picker, and the fact that you're pledging to an issue in an org that you're a maintainer of.

Because `[organization]` in the route matches the name of an organization that you're a maintainer of, it picks that org in the picker instead of defaulting to your backer profile.

You can verify this by viewing the pledge page of an org that you're not a maintainer of, like: https://polar.sh/TanStack/query/issues/5913

I think that the public pages should _always_ be "used" as your backer profile, and never as an organization.

This could be handled by the `useCurrentOrgAndRepoFromURL` hook, by making it behave differently on "public" vs "maintainer" pages. As a bonus, we don't need to add any state to handle this. ;-)

**Comment by birkjernstrom** [comment]
Great clarification and callout @zegl! Completely agree that the public pages should always be used as the backer profile and like the recommended approach of setting that rule to avoid having additional state.
