### ISSUE TITLE
SVG Badge is not showing in GitHub notifications emails 

### ISSUE THREAD

**Issue by drunkwcodes** [polarsource/polar#1182]
The link is alright but the button image is missing.
Perhaps it's trivial.

![image](https://github.com/polarsource/polar/assets/36228443/b5ab5913-dfbf-4fe1-b17a-ec39f8606da3)

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/polarsource) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog :^)

<a href="https://polar.sh/polarsource/polar/issues/1182">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/polarsource/polar/issues/1182/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/polarsource/polar/issues/1182/pledge.svg">
</picture>
</a>

**Comment by frankie567** [comment]
Thank you for the report, @drunkwcodes 🙏

I would say this is *somewhat* expected since our badge is a SVG image. Gmail doesn't support them.

Tackling this is quite complex 🤔 The solution is see right now would be to check for the `User-Agent` and try to detect if the request comes from Gmail. If so, we could return a fallback PNG image instead of the SVG badge.

**Comment by frankie567** [comment]
For the record, here is the user-agent I catched from Gmail client: `Mozilla/5.0 (Windows NT 5.1; rv:11.0) Gecko Firefox/11.0 (via ggpht.com GoogleImageProxy)`

**Comment by frankie567** [comment]
Closing as we probably won't dedicate time for this, lot of other focuses right now 😄
