### ISSUE TITLE
Implement a `/funding` Public API

### ISSUE THREAD

**Issue by frankie567** [polarsource/polar#1321]
# 👀 What?

When working on the #1317, I noticed we didn't have a one-stop way to retrieve issues with their pledges data. It's something that could be helpful to nicely display the current amount funded by type, a sample of pledgers, the funding goal, etc.

# 📓 Decision log

After a nice brainstorming with @zegl, we decided the following:

* ❌ We don't want to add pledges data directly inside the `/issues` API. We want to keep clear separation of concerns/ownership.
* ✅ Introduce a new `/funding` Public API which would be able to return this data. Basically, the schema would look like this:

```py
# Naming not final

class FundingSummaryIssue(Schema):
    issue: Issue
    total: CurrencyAmount
    funding_goal: CurrencyAmount | None
    summary: PledgesSummary


class PledgesSummary(Schema):
    pay_upfront: PledgeTypeSummary
    pay_on_completion: PledgeTypeSummary


class PledgeTypeSummary(Schema):
    total: CurrencyAmount
    pledgers: list[Pledger]
```

Ultimately, this API could help us to:

* Remove the `funding` property from `Issue` schema
* Improve how we query data from dashboard?
* Improve how we query data for the GitHub badge?

**Comment by birkjernstrom** [comment]
This is great and makes a lot of sense!

Just two small thoughts.
1. I think we should s/pledge/funding as a naming convention since `pledge` is more a verb tied to "on completion" now and funding is the umbrella & public term of the action (upfront or on completion).
2. Rename `pledgers` to `backers` given the above + I think `backers` should be our name for it.

I know this would be different from legacy code before these new terms, but I think that's something we can clean-up separately if we agree this is the best naming conventions moving forward to keep it consistent.

**Comment by frankie567** [comment]
@birkjernstrom I understand the motivation but I would prefer to stick with our current naming for now and change it everywhere in a dedicated project/effort. I would like to avoid the messy situation where the API has several names for the same thing.

Besides that, @zegl already needs to use the schemas I'm defining here, so we would step on each other's feet by doing this now 😅

**Comment by birkjernstrom** [comment]
Makes total sense - I’m onboard with that [image: 👍]
