### ISSUE TITLE
Same Stripe account name for maintainers & contributors

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#1729]
We create separate Stripe accounts for maintainers & contributors. Arguably, a feature request would be to "link" an account a user has admin access to across their Polar accounts (backer/contributor or maintainer). However, I think it's good we separate them as we do – clear separation of concern since it's different transactions, accounting events, tax implications etc.

However, the issue is that both use the "Polar" name (see below). Which understandably causes confusion for the end user. We should investigate whether we can easily name them differently so we can clarify this over at Stripe.

<img width="400" alt="image" src="https://github.com/polarsource/polar/assets/281715/99d0552c-ec80-44ff-b8cc-90832d12a128">
<img width="514" alt="image" src="https://github.com/polarsource/polar/assets/281715/6f692cea-c757-4a06-ab87-94cb35307501">

**Comment by birkjernstrom** [comment]
Separately, I think this also highlights the confusion around or navigation between "Backer" vs. "Maintainer" when it comes to individual organizations (maintainers) vs. the individual as a backer (personal account). In case it's a true organization with a different name, it's clear, but otherwise at first glance it's hard to distinguish between being in the backer vs. maintainer state and consequently easy to mistake our Stripe setup nudge to relate to the same account being prompted "twice".

**Comment by frankie567** [comment]
I digged a bit on this, and it seems Stripe has a value for this on their Account object: https://stripe.com/docs/api/accounts/object#account_object-settings-dashboard-display_name

One my personal account on Polar, it's set to `null`.

The thing is, it doesn't seem to be possible to set it through the API. I tried, but the API refuses this parameter.

**Comment by fabiocaccamo** [comment]
@birkjernstrom thank you for the clarification. 

I think that just changing the display name to something like `Polar (Baker)` / `Polar (Maintainer)` would be clear enough.

**Comment by zegl** [comment]
As there does not seem to be any public API available to set this name, I've contacted Stripe support to see what they recommend us to do. :)

**Comment by zegl** [comment]
It's unclear how (I have not found any documentation, nor have the Support been any helpful). But it seems like if there are multiple accounts from the same Platform, and the `business_profile.name` has been set (which is not the same as the read-only `settings.dashboard.display_name`). The value from `business_profile.name` will be used to differentiate between the accounts in Stripe Express.

_To complicate testing, Stripe Express in test-mode does not have this problem, as Stripe Express accounts in test-mode are limited to one account_.

Example:

<img width="393" alt="Screenshot 2023-11-23 at 14 21 46" src="https://github.com/polarsource/polar/assets/47952/d56189a9-e1e6-4a00-88ad-b2feeac02963">

If the user manually overrides the display_name from the Stripe Express dashboard, the value that the user set is always used.

In my testing, the `business_profile.name` was set to `"github.com/zegloforko (org)"`, and the first 22 characters of this name seems to have been used in Stipe Express, truncating it to `"github.com/zegloforko "`, which is why it looks a bit weird in the screenshot.

Currently (as of #1742) we're using the following names of the accounts:

* `github.com/NAME (org)`
* `github.com/NAME (user)`

I propose to change this to:

* `NAME` for non-personal organisations (example: `polarsource`)
* `org/NAME` for personal organisations (example: `org/zegl`)
* `user/NAME` for users (example: `user/zegl`).

**Comment by birkjernstrom** [comment]
Great work on this @zegl!! Knowing the frustrating support endeavour you had especially - awesome to see that you found a solution. Solid tinkering :)
