### ISSUE TITLE
Post: Shortcut to add YouTube embed

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#2341]
Make it more clear that YouTube embeds are supported by adding it as a component in our list and supporting a shorthand, e.g

```
<YouTube url="" />
```

**Comment by isaacharrisholt** [comment]
Can I take this one?

**Comment by zegl** [comment]
I 100% agree that we should showcase the YouTube embed functionality in a better way! 

I think we should wait implementing new components until we've solved the underlying discoverability issue. We already support YouTube embeds via a custom `<iframe>` wrapper, so a new custom `<YouTube />` or `<Video />` component wouldn't add any functionality.

The idea behind using `<iframe>` vs `<YouTube />` is that if you copy/paste an embed code from YouTube, it should work out of the box. And it does!

Example:

```
<iframe width="560" height="315" src="https://www.youtube.com/embed/z050M9RWdME?si=pA3K2MxE3oAA78Sh" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
```

or you can skip everything except the src, and get the same results:

```
<iframe src="https://www.youtube.com/embed/z050M9RWdME" />
```

---

I think that we should rework how we teach users about our custom components. Some (collapsible?) sidebar to the right of the editor maybe? 

We could also extend how the `<iframe>` works, by supporting more `src` formats to make it easier to use. We could support the "normal" YouTube URLs in the src and convert it to the "embed" URLs, so that 
`<iframe src="https://www.youtube.com/watch?v=z050M9RWdME" />` would be the same as the embed variant above.

**Comment by isaacharrisholt** [comment]
@zegl you're right. This idea stemmed from a conversation Birk and I were having on Discord where I mentioned that it was unclear you could just use HTML in the post editor. I like the sidebar idea. Perhaps it should be similar to the GitHub `Markdown is supported` button and shows a list of all available editor features (e.g. image copy-paste, video embeds, supported HTML tags, etc.)

**Comment by zegl** [comment]
A new YouTube-embed wizard has been shipped in the posts editor! 🚀
