### ISSUE TITLE
Remove repositories-only subscription tiers and benefits  

### ISSUE THREAD

**Issue by frankie567** [polarsource/polar#3213]
This has been implemented but never used (not even exposed in the UI).

Unless we can think of good use-cases for it, or expect to be a popular user feedback in the future I think this can be removed.

Thoughts?

**Comment by birkjernstrom** [comment]
I think I agree - let me stew on it a bit in the context of the below.

I believe we'll want to decouple our "organizations" and GitHub this year. Allowing developers/creators to easily setup their own organizations, i.e containers for different monetization offerings. They could then easily create new ones and link/upsell/connect them to specific repos as they choose. Instead of coupling ourselves even more to GitHub and their organization+repository structure.

Of course, a lot of challenges with that decoupling (usernames, orgnames and corresponding slugs). But I believe that will provide complete flexibility & enable the "intent of this feature" without the strong coupling which it currently has and thankfully has not exposed.

**Comment by frankie567** [comment]
So, I suppose we agree here to proceed on the removal ? :)

It'll ease lot of things and speed up the migration for Organization-level tokens.

**Comment by birkjernstrom** [comment]
Yes, let's do it 😎
