### ISSUE TITLE
Stuck on: `Connecting your amazing repositories...`

### ISSUE THREAD

**Issue by pktiuk** [polarsource/polar#3254]
Hello,

I wanted to add my organization to Polar, but after linking polar app with my account I got stuck on the screen with message:
`Connecting your amazing repositories...`

(It takes already more than 20 minutes...)

**Comment by pktiuk** [comment]
@birkjernstrom  

> You can refresh the page without the state/sync getting paused or anything.

I already refreshed it. Even after opening this proper link `https://polar.sh/github/installation?installation_id=50374038&setup_action=install` I can still see this prompt. For now I just unauthorized polar app on GitHub and I will try again later.

> Or going to polar.sh/maintainer should show that the organization is already setup with everything.

My organization is not visible here.

**Comment by birkjernstrom** [comment]
That's strange and certainly a bug then. What browser/OS are you using and do you see any errors in the console on the browser?

Will try to replicate & fix it today. Sorry about the inconvenience here @pktiuk

**Comment by birkjernstrom** [comment]
Couldn't reproduce @pktiuk :( Any chance you can try again and see if you can share any errors in the network/console tab? Definitely want to fix this in the event some edge cases causes issues, but having a hard time pinning it down.

**Comment by pktiuk** [comment]
@birkjernstrom    
After reopening the link I posted above I saw these errors in the console. 

![obraz](https://github.com/polarsource/polar/assets/45544416/294faa16-5d59-4c8d-9b96-df7a4eba1d06)

**Comment by pktiuk** [comment]
English version:

![obraz](https://github.com/polarsource/polar/assets/45544416/9b037a33-3999-4a25-8415-6a9ffa516d16)

**Comment by birkjernstrom** [comment]
Thanks @pktiuk - I managed to trace down the issue from a GitHub API call. Still a bit unclear what happened & how to reproduce, but now the source is clear so I'll figure it out.

I had a look and the organization has been created in our database since and connected to your user. So by now you should be able to see it if you logout/login? By clicking & switching profiles in the navigation like so:

<img width="316" alt="image" src="https://github.com/polarsource/polar/assets/281715/59fee871-87de-446f-b4f1-95f7aa9bd8bc">

**Comment by pktiuk** [comment]
@birkjernstrom   
Thank you, now I can see this org

**Comment by pktiuk** [comment]
But my issues are not fetched from GitHub. Only 1 out of 102 is fetched

**Comment by birkjernstrom** [comment]
Oh right. Because of the initial error the synchronization was never triggered, but new issues would come in (webhooks). I've gone ahead and triggered the synchronization task and now there are 102 issues connected to the repository. 

Really sorry for this poor onboarding experience. The underlying issue was that we got a `401` or `403` from GitHub in the request to fetch active installations once you where redirected back to us. So we couldn't get the new installation. I almost suspect there might be a race condition at play here between Polar & GitHub and the redirect. Hard to pin point exactly.

I'll add better error handling at least on our side & some more logging so that in case this happens again, we'll have more to operate on to resolve the issue.

**Comment by pktiuk** [comment]
> Really sorry for this poor onboarding experience.

Don't worry, I know, that I am an early adopter. I appreciate what you do out there and I hope you will succeed.
