### ISSUE TITLE
paramters

### ISSUE THREAD

**Issue by webbrowser11** [polarsource/polar#3956]
in the file https://github.com/polarsource/polar/blob/main/dev/setup-environment.py
does the GitHub app setup FAIL protocol use parameters?
along with the .format function or whatsoever just wondering if it actually shows failing parameters.
or would someone need to add parameters like this:

`params = {'error': 'Invalid token'} #or what-so-ever`
`html = """`
`<!DOCTYPE html>`
`<html>`
`<head>`
`    <title>GitHub App Setup</title>`
`</head>`
`<body>`
`    <h1>GitHub App Setup</h1>`
`    <p>Failed to setup the GitHub App</p>`
`    <p>Params: {params}</p>`
`</body>`
`</html>`
`""".format(params=params)`

**Comment by webbrowser11** [comment]
just wondering if there is any fixing needed here. and if this would maybe cause confusion for a user if it just said:
Params: {params} at the bottom of the page.

**Comment by birkjernstrom** [comment]
Hey @webbrowser11. The `CALLBACK_ERROR_PAGE` string template is used with `.format` on line 169 below. https://github.com/polarsource/polar/blob/7be2f29710f1ca18c6739555de883f13f3b20b2a/dev/setup-environment.py#L169

In this case, I think since the errors can vary it's mostly helpful to get the query parameters to be able to debug the issue. If we see (or hear) about common issues in the future, we'd love to provide more helpful & custom error messages on how to resolve them specifically.

Don't hesitate to file an issue if you had any problem setting up the development environment.

**Comment by webbrowser11** [comment]
okay thanks!
