### ISSUE TITLE
[Feature request] Handle changes in the Issues shortly after creating an issue

### ISSUE THREAD

**Issue by pktiuk** [polarsource/polar#4074]
Some users often create a new issue in a repository and edit it almost instantly after creation (because they forgot about  something or issue is not rendering correctly etc.)

In such a situation this user can by accident delete note left by Polar, because Polar added a note on the bottom when such a user was editing their post.

Please look at this issue as an example (I needed to add Fund badge to trigger polar again):

`https://github.com/AntiMicroX/antimicrox/issues/1048`

**Comment by birkjernstrom** [comment]
Sorry for not seeing and responding to this one sooner @pktiuk. 

I'm afraid this is intentional. We have explicit logic to check for this scenario, e.g a Polar badge was embedded and then manually removed. In such a case we back-off and do nothing (noop). Since this ensures:
1) Developers can manually remove the badge in case they use Polar with automatic embeds on all issues by default
2) We don't take an action without the consent/intent of the developer. Both in case of the above + even in case they remove it with manual embeds (by label)

The cases above are a lot more common I believe vs. making quick changes and accidentally removing the Polar label. In the latter case, I think re-labelling to badge again is a better smaller & rare inconvenience vs. Polar constantly embedding the badge unless users un-label the issue (and not supporting defaulting to automating embeds on all issues with manual removal).

I hope this context helps explain the design choices here.
