### ISSUE TITLE
Create Pre-defined Templates for New Issue and Pull Request to Standardize Contributions

### ISSUE THREAD

**Issue by apsinghdev** [polarsource/polar#4102]
When we create a new issue or raise a pull request, we have to think by ourselves about what information we need to add for the issues or PR. Having pre-defined templates for creating a new issue and raising a pull request would be a good idea. It can benefit us in these manners:

1. We don't have to think "What information do I need to provide?"
2. Provides a consistent format for reporting bugs or feature requests.
3. Standardized templates make it easier to review and understand submissions.
4. Prompts users/contributors to include necessary details, reducing back-and-forth.
5. Structured PR templates help reviewers assess changes more efficiently.

Below are some of the sample screenshots of how this feature would look like (If implemented):

<img width="1278" alt="Screenshot 2024-10-06 at 1 25 39 PM" src="https://github.com/user-attachments/assets/9be1c088-0945-4c43-a86b-4d5263500b26">
<img width="971" alt="Screenshot 2024-10-06 at 1 27 27 PM" src="https://github.com/user-attachments/assets/edf7c5c5-5595-491b-8337-27cc2d7ad031">
<img width="1104" alt="Screenshot 2024-10-06 at 1 28 34 PM" src="https://github.com/user-attachments/assets/47981b4a-958c-4058-99cd-8396062e77c2">

**Comment by apsinghdev** [comment]
@frankie567 what're your thoughts on this?

**Comment by frankie567** [comment]
That's interesting @apsinghdev, thank you! A few comments:

* I agree that an Issue template would be useful. However, I think I prefer traditional plain-text templates instead of the new form-style templates. It gives more flexibility IMO.
* The template you propose looks great. I would just remove the version (doesn't really apply to us) and the disclaimer checkboxes
* For Feature Request and Improvement, I would prefer to have a link (using the [`contact_links` configuration](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser)) towards https://github.com/orgs/polarsource/discussions/new?category=feature-requests, so that's directed to Discussions directly instead of an Issue.
* I would also like to have a link to our [Discord](https://discord.gg/STfRufb32V) for support requests (i.e. another `contact_links` item).

**Random thoughts**

* An emoji (🪲, 💡 and 🛟) could be nice in the front of the title of each item

**Comment by apsinghdev** [comment]
> That's interesting @apsinghdev, thank you! A few comments:
> 
> * I agree that an Issue template would be useful. However, I think I prefer traditional plain-text templates instead of the new form-style templates. It gives more flexibility IMO.
> * The template you propose looks great. I would just remove the version (doesn't really apply to us) and the disclaimer checkboxes
> * For Feature Request and Improvement, I would prefer to have a link (using the [`contact_links` configuration](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser)) towards https://github.com/orgs/polarsource/discussions/new?category=feature-requests, so that's directed to Discussions directly instead of an Issue.
> * I would also like to have a link to our [Discord](https://discord.gg/STfRufb32V) for support requests (i.e. another `contact_links` item).
> 
> **Random thoughts**
> 
> * An emoji (🪲, 💡 and 🛟) could be nice in the front of the title of each item

Thanks for your input. Onto it. I'll raise a PR soon.
