### ISSUE TITLE
When creating orders/transactions from Stripe, use their creation timestamp instead of generating ours

### ISSUE THREAD

**Issue by frankie567** [polarsource/polar#4396]
When we receive an `invoice.paid` event from Stripe, we create a corresponding Order in our system. Naturally, we let the `created_at` property to the default, i.e. `NOW()`. Similarly, we create payment transactions when receiving payment success events.

It could be nice to use instead the creation timestamp provided by Stripe (i.e. their invoice or payment creation date). It doesn't make a difference in production, but in local development, it could be really nice when using Test Clocks: we can advance time in Stripe and our orders/transactions would also reflect that simulated time.

**Comment by magarpratik** [comment]
Hi, I’d love to work on this issue if it's available. I can look at this next week.

If that's okay, could you please assign it to me? 

Thanks!

**Comment by frankie567** [comment]
Sure, no problem!

**Comment by magarpratik** [comment]
Hi @frankie567,

I've created a [draft PR](https://github.com/polarsource/polar/pull/4569) to address the issue, where the order creation logic triggered by an `invoice.paid` event has been updated to use the Stripe-generated `created` timestamp for the `created_at` property.

Is this sufficient, or is more work required? I'm asking because the [issue description](https://github.com/polarsource/polar/issues/4396#issue-2640985500) suggests we might want to apply similar changes to payment success events as well.

If that's the case, could you clarify which of the following events should be considered "payment success" events?

```
DIRECT_IMPLEMENTED_WEBHOOKS = {
    "payment_intent.succeeded",
    "payment_intent.payment_failed",
    "charge.succeeded",
    "charge.refunded",
    "charge.dispute.created",
    "charge.dispute.funds_reinstated",
    "customer.subscription.created",
    "customer.subscription.updated",
    "customer.subscription.deleted",
    "invoice.paid",
}
```

Code snippet taken from [here](https://github.com/polarsource/polar/blob/5df36c74a93e600df263138679fd670043048eeb/server/polar/integrations/stripe/endpoints.py#L19).
