### ISSUE TITLE
Docs: Make them fast again

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#4529]
Our docs sometimes become slow due to suddenly having to read, parse & transform our OpenAPI schema upon request vs. cached as the intent.

We consistently fix this, but then NextJS stops rendering them statically again. Probably skill issues (😅), but it's annoying and error prone. 

We should investigate a more long-term solution to ensure fully static pages and faster response times.

**Comment by frankie567** [comment]
I think it's probably related to the fact that we add dynamic inputs to each properties.

Sad to say but after few considerations I would say:

1. It's a darling. I don't think it's really used or useful
2. It's half-baked, especially since we're not able to update the SDK snippets accordingly
3. It slows us down.

My call: kill the feature and keep only static information. 99% sure it'll solve those problems for good.

**Comment by frankie567** [comment]
I was wrong :/ Investigating!

**Comment by birkjernstrom** [comment]
Ok interesting & strange - felt like a good theory.

However, feel free to remove the dynamic inputs if you want. To your point, it's half-baked now and we have other ideas for the near-term of how we can increase the DX to get the customers own variables.

**Comment by frankie567** [comment]
So, it was definitely it but I missed something in the first attempt: add instruction to Next.js to force a static rendering (which seems to be disabled by default if we use `generateStaticParams`):

```ts
export const dynamic = 'force-static'
```

Now we're speed 🏎️
