### ISSUE TITLE
Separate "Closed" & "Completed"

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#568]
Tangental feedback that emerged through a discussion.

Comment: Maintainers sometimes click "close" by accident and re-open a bit later. Do we trigger the pledge completed status and follow-on emails etc directly? Perhaps we should wait?

However, furthermore we might want to have some sanity check on whether any effort exists.

**Comment by birkjernstrom** [comment]
We should discuss this one a bit first. Lots of nuances and design choices to make to avoid creating a weird distinction between "Closed" & "Completed"

**Comment by hult** [comment]
Perhaps if we sent an email requiring them to confirm a close (for any reason), and perhaps have an auto-confirm after a certain time? Would of course further extend the time until payout.

**Comment by zegl** [comment]
Just started thinking about this, will not code much until we've talked and thought things through a bit more.

For recap, issues on the dashboard currently have five different states that are all dynamically calculated (they are not persisted):

* `completed` (issue is closed)
* `pull_request` (not `completed` and at least one non-draft PR that mentions the issue exists)
* `in_progress` (not `completed` or `pull_request`, and at least one draft PR that mentions the issue exists)
* `triaged` (not any of the above, and at least one assigned user exists)
* `backlog` (not any of the above)

Pledges also have states (`created`, `pending`, `paid`, `refunded`, `disputed`, etc), and are currently independent from the status of the issues. 

The use case for this issue and #664 both seem to be to delay moving _pledge_ statues to `pending` when the backed issue is closed, and very little about the user being able to filter on the status of pledges on the dashboard ("which issues have pledges that I have not yet confirmed for payout?").

One thing that's different for our issue statuses and the pledge statuses, is that they can move "backwards". If a `completed` issue is re-opened, the issue status will change back to it's previous status. If it had any pledges, the pledges move from `created` to `pending` when the issue is closed, and will stay in `pending` if the issue is re-opened.

```
1. Start               issue=`backlog`  pledge=`created`
2. Issue is closed     issue=`closed`   pledge=`pending`  (this also sends emails to pledgers)
3. Issue is re-opened  issue=`backlog`  pledge=`pending`  (pledge is now stuck here)
```

An alternative (that I'm kind of starting to like), is to add this extra step as a state to the **pledge** instead of to the issue. It could be an extra step between `created` and `pending` for this `waiting_for_confirmation` state.

```
`created` --( issue closed )--> `waiting_for_confirmation`
`waiting_for_confirmation` --( issue re-opened )--> `created`
`waiting_for_confirmation` --(confirmed or timeout)--> `pending`
```

And from the pending state, the existing pending flow would stay as before, with it's 14d dispute window before getting paid out.

What do you think?

**Comment by petterheterjag** [comment]
It makes sense from my perspective too.

**Comment by hult** [comment]
:+1:

**Comment by birkjernstrom** [comment]
Closing this. Merged into https://github.com/polarsource/polar/issues/664 based on our discussion + linking to Gustav's comment for the great context on the design choice.
