### ISSUE TITLE
Auth page in Phone is not aligned and small

### ISSUE THREAD

**Issue by Mahmoudgalalz** [polarsource/polar#853]
When I tried to log in with my phone the button is not aligned and small

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/polarsource/polar/issues/853">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/polarsource/polar/issues/853/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/polarsource/polar/issues/853/pledge.svg">
</picture>
</a>

**Comment by birkjernstrom** [comment]
Thank you @Mahmoudgalalz! Unfortunately, our dashboard is not fully mobile optimized at this stage, but something we should fix.

**Comment by Mahmoudgalalz** [comment]
I can work on making it responsive, so should I start?
I see Polar uses tailwind, I can work on this if you are planning

**Comment by birkjernstrom** [comment]
Sure, that would be much appreciated if you're interested.

However, best to contain it to this specific issue of the login screen. Both because isolated PRs are great, but mainly because...

Our dashboard is implemented to be responsive, but it's not 100% there and the main things needed are related to:
1. How we manage the navigation on mobile
2. How we condense the issue details on mobile

Both of those would need design decisions. So wouldn't be fair to have you embark on them without much guidance of the intended design :-) So let's wait with those for now.

Does that work for you @Mahmoudgalalz ?

**Comment by Mahmoudgalalz** [comment]
The issue is happening cuz of the drawing in the background, which make the layout smaller, I will push a PR now

**Comment by birkjernstrom** [comment]
Thank you @Mahmoudgalalz! Today has been a bit busy, but I'll test the PR first thing tomorrow morning. Can't remember exactly why the height was there to begin with. Just need to confirm it's not a necessary hack to achieve sufficient height of our sidebar or equivalent on desktop.

**Comment by birkjernstrom** [comment]
Fixed in https://github.com/polarsource/polar/pull/889
