### ISSUE TITLE
Discord invite in the README is broken

### ISSUE THREAD

**Issue by jclangst** [polarsource/polar#886]
![image](https://github.com/polarsource/polar/assets/13301098/2d5c7294-9a49-41cc-88cc-a8e74f74338d)

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/polarsource/polar/issues/886">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/polarsource/polar/issues/886/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/polarsource/polar/issues/886/pledge.svg">
</picture>
</a>

**Comment by birkjernstrom** [comment]
Thanks for reporting this @jclangst! This is very strange; I regenerated the link, but Discord gives me the same one when configuring it to not expire, have no limit etc. I also tried it myself and it worked... Can you try again?

Otherwise here is a link setup for 7 days and 25 uses to ensure a unique link was generated: https://discord.gg/VxEMfZbw

Hope to see you in the channel soon and apologies for the issues joining, I really hope it works now
